car:
  storage.location: uploadPosts
  posts.pageSize: 5

logging.level:
  root: info
  org:
    hibernate:
      SQL: warn
      orm.jdbc.bind: warn


spring:
  sql.init.mode: always
  thymeleaf:
    cache: false
    template-resolver-order: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: "*"
