-- liquibase formatted sql

-- changeset mibmy:1666659392198-1
CREATE TABLE account
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE,
    firstname   VARCHAR(255),
    name        VARCHAR(255),
    login       VARCHAR(255),
    password    VARCHAR(255),
    phonenumber VARCHAR(255),
    city_id     BIGINT,
    CONSTRAINT account_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-2
CREATE TABLE body
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image VARCHAR(25),
    name  VARCHAR(20)                             NOT NULL,
    CONSTRAINT body_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-3
CREATE TABLE car
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created              TIMESTAMP WITHOUT TIME ZONE,
    description          VARCHAR(1000),
    enginedisplacement   SMALLINT,
    lastupdated          TIMESTAMP WITHOUT TIME ZONE,
    name                 VARCHAR(80),
    odometer             SMALLINT,
    power                SMALLINT,
    price                numeric(38, 2),
    status               VARCHAR(20),
    year                 SMALLINT,
    yearpurchase         SMALLINT,
    account_id           BIGINT,
    body_id              BIGINT,
    city_id              BIGINT,
    color_id             BIGINT,
    engine_id            BIGINT,
    gearbox_id           BIGINT,
    generations_id       BIGINT,
    mark_id              BIGINT,
    model_id             BIGINT,
    modification_mark_id BIGINT,
    modification_name    VARCHAR(30),
    modification_year_id SMALLINT,
    transmission_id      BIGINT,
    CONSTRAINT car_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-4
CREATE TABLE city
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(30),
    CONSTRAINT city_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-5
CREATE TABLE color
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color VARCHAR(20),
    name  VARCHAR(20),
    CONSTRAINT color_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-6
CREATE TABLE engine
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image VARCHAR(20),
    name  VARCHAR(20)                             NOT NULL,
    CONSTRAINT engine_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-7
CREATE TABLE gearbox
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image VARCHAR(20),
    name  VARCHAR(20)                             NOT NULL,
    CONSTRAINT gearbox_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-8
CREATE TABLE generations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image           VARCHAR(50),
    name            VARCHAR(50),
    year            SMALLINT,
    body_id         BIGINT,
    engine_id       BIGINT,
    gearbox_id      BIGINT,
    model_id        BIGINT,
    mark_id         BIGINT,
    name_id         VARCHAR(30),
    year_id         SMALLINT,
    transmission_id BIGINT,
    CONSTRAINT generations_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-9
CREATE TABLE mark
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image VARCHAR(20),
    name  VARCHAR(20)                             NOT NULL,
    CONSTRAINT mark_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-10
CREATE TABLE model
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(20)                             NOT NULL,
    mark_id BIGINT,
    CONSTRAINT model_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-11
CREATE TABLE options
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(80),
    namecategory VARCHAR(30),
    CONSTRAINT options_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-12
CREATE TABLE transmission
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image VARCHAR(25),
    name  VARCHAR(15)                             NOT NULL,
    CONSTRAINT transmission_pkey PRIMARY KEY (id)
);

-- changeset mibmy:1666659392198-13
ALTER TABLE account
    ADD CONSTRAINT uk_5vxwyorsr92jce3ore6h93k6q UNIQUE (login);

-- changeset mibmy:1666659392198-14
ALTER TABLE body
    ADD CONSTRAINT uk_sayvk07ixf023kg7a38epdc UNIQUE (name);

-- changeset mibmy:1666659392198-15
ALTER TABLE city
    ADD CONSTRAINT uk_qsstlki7ni5ovaariyy9u8y79 UNIQUE (name);

-- changeset mibmy:1666659392198-16
ALTER TABLE color
    ADD CONSTRAINT uk_n3axgangk6yuxhrb2o7fk9oa7 UNIQUE (name);

-- changeset mibmy:1666659392198-17
ALTER TABLE engine
    ADD CONSTRAINT uk_namnc97tmp37w2i7tg024ghgj UNIQUE (name);

-- changeset mibmy:1666659392198-18
ALTER TABLE gearbox
    ADD CONSTRAINT uk_e0ayoygrseeb2kmwfsklt4fol UNIQUE (name);

-- changeset mibmy:1666659392198-19
ALTER TABLE generations
    ADD CONSTRAINT uk2mfj7a9nmtkfp1um5av5f64ua UNIQUE (name, year, body_id, engine_id, gearbox_id,
                                                       model_id, mark_id, name_id, year_id,
                                                       transmission_id);

-- changeset mibmy:1666659392198-20
ALTER TABLE mark
    ADD CONSTRAINT uk_2wvci4bf6bfoys5vfwsbomn0o UNIQUE (name);

-- changeset mibmy:1666659392198-21
ALTER TABLE model
    ADD CONSTRAINT uk_ca0u5wgwbvi61aty72boerxqy UNIQUE (name);

-- changeset mibmy:1666659392198-22
ALTER TABLE options
    ADD CONSTRAINT uk_9o64ripk4tkpj6osqw3d3mpcf UNIQUE (name);

-- changeset mibmy:1666659392198-23
ALTER TABLE transmission
    ADD CONSTRAINT uk_h8s4ghrx9ltef2wft6jju1j3o UNIQUE (name);

-- changeset mibmy:1666659392198-24
CREATE TABLE car_options
(
    car_id     BIGINT NOT NULL,
    options_id BIGINT NOT NULL,
    CONSTRAINT car_options_pkey PRIMARY KEY (car_id, options_id)
);

-- changeset mibmy:1666659392198-25
CREATE TABLE generations_options
(
    generations_id BIGINT NOT NULL,
    options_id     BIGINT NOT NULL,
    CONSTRAINT generations_options_pkey PRIMARY KEY (generations_id, options_id)
);

-- changeset mibmy:1666659392198-26
CREATE TABLE image
(
    car_id       BIGINT  NOT NULL,
    filename     VARCHAR(255),
    images_order INTEGER NOT NULL,
    CONSTRAINT image_pkey PRIMARY KEY (car_id, images_order)
);

-- changeset mibmy:1666659392198-27
CREATE TABLE modification
(
    name                VARCHAR(30) NOT NULL,
    year_id             SMALLINT    NOT NULL,
    enginedisplacement  SMALLINT    NOT NULL,
    numberofcylinders   SMALLINT    NOT NULL,
    positionofcylinders VARCHAR(15),
    power               SMALLINT    NOT NULL,
    mark_id             BIGINT      NOT NULL
);

-- changeset mibmy:1666659392198-28
ALTER TABLE modification
    ADD CONSTRAINT modification_pkey PRIMARY KEY (mark_id, name, year_id);

-- changeset mibmy:1666659392198-29
ALTER TABLE car
    ADD CONSTRAINT engine_id_fk FOREIGN KEY (engine_id) REFERENCES engine (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-30
ALTER TABLE modification
    ADD CONSTRAINT fk1hm5c3i8ij09743lyn2fv14rk FOREIGN KEY (mark_id) REFERENCES mark (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-31
ALTER TABLE car
    ADD CONSTRAINT fk2y1m0j23bbn5b9x7wo3i28ipx FOREIGN KEY (gearbox_id) REFERENCES gearbox (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-32
ALTER TABLE car_options
    ADD CONSTRAINT fk3amwq3lj0keuxomvla2sy79nr FOREIGN KEY (car_id) REFERENCES car (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-33
ALTER TABLE account
    ADD CONSTRAINT fk3h9n1sl4qpxc32vks85k7302h FOREIGN KEY (city_id) REFERENCES city (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-34
ALTER TABLE generations_options
    ADD CONSTRAINT fk4gwxsl13wjap77kl7l78t2med FOREIGN KEY (options_id) REFERENCES options (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-35
ALTER TABLE car
    ADD CONSTRAINT fk4mt4rf2euhd4unu8yo9qxi85e FOREIGN KEY (mark_id) REFERENCES mark (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-36
ALTER TABLE generations
    ADD CONSTRAINT fk5jmnoncn0o3a5o7xoaspcpv4e FOREIGN KEY (mark_id, name_id, year_id) REFERENCES modification (mark_id, name, year_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-37
ALTER TABLE generations
    ADD CONSTRAINT fk6yoh94tnbermq03xu2oluiy5h FOREIGN KEY (engine_id) REFERENCES engine (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-38
ALTER TABLE car
    ADD CONSTRAINT fk772uqy9hm5yicyxh9t6x6vusr FOREIGN KEY (model_id) REFERENCES model (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-39
ALTER TABLE car_options
    ADD CONSTRAINT fk7wpn4vntjlidx2c0oa2csd8jy FOREIGN KEY (options_id) REFERENCES options (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-40
ALTER TABLE generations
    ADD CONSTRAINT fk9uopb9u7lj9d8bmsu1hd023gg FOREIGN KEY (gearbox_id) REFERENCES gearbox (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-41
ALTER TABLE car
    ADD CONSTRAINT fkb7h0v1qtngg6qiw64obcpxdr8 FOREIGN KEY (city_id) REFERENCES city (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-42
ALTER TABLE generations
    ADD CONSTRAINT fkbou3iu2qs4ob719q6ehxrnvce FOREIGN KEY (body_id) REFERENCES body (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-43
ALTER TABLE car
    ADD CONSTRAINT fkc7gc9o27725itqj9kfg6abkvp FOREIGN KEY (generations_id) REFERENCES generations (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-44
ALTER TABLE image
    ADD CONSTRAINT fkc7rj1xc1xqxuej65kr7oqhw0u FOREIGN KEY (car_id) REFERENCES car (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-45
ALTER TABLE generations
    ADD CONSTRAINT fkci9h1mitxoiaqe2kphl1ejk6w FOREIGN KEY (transmission_id) REFERENCES transmission (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-46
ALTER TABLE car
    ADD CONSTRAINT fkdvm7535riwqbql65a4otb50yh FOREIGN KEY (transmission_id) REFERENCES transmission (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-47
ALTER TABLE car
    ADD CONSTRAINT fkg0jvjcwntclcjd9cd2vmta820 FOREIGN KEY (color_id) REFERENCES color (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-48
ALTER TABLE generations_options
    ADD CONSTRAINT fkhaai8cnbihkdydvpqdag1yvsc FOREIGN KEY (generations_id) REFERENCES generations (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-49
ALTER TABLE generations
    ADD CONSTRAINT fkl53sv288blk5tk6djfpd29h00 FOREIGN KEY (model_id) REFERENCES model (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-50
ALTER TABLE car
    ADD CONSTRAINT fkl8090y1a4x9uafi7qyfvqtq3m FOREIGN KEY (modification_mark_id, modification_name,
                                                            modification_year_id) REFERENCES modification (mark_id, name, year_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-51
ALTER TABLE car
    ADD CONSTRAINT fkmyssvrbr6bwoaasc7l4j1mfj1 FOREIGN KEY (account_id) REFERENCES account (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-52
ALTER TABLE car
    ADD CONSTRAINT fkrf5vjaxr3qqub08xdittqa9lj FOREIGN KEY (body_id) REFERENCES body (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset mibmy:1666659392198-53
ALTER TABLE model
    ADD CONSTRAINT fktj5rabfi6sypr43683jbhs78g FOREIGN KEY (mark_id) REFERENCES mark (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

